### PR TITLE
[Gcard 100] add createComment method

### PR DESCRIPTION
**Pull request by ridemountainpig**
feat: add create comment method

### CODE REVIEW

**Review by davidho0403 — CHANGES_REQUESTED** [review]
@pascal910107 do you have better idea?

**Review by davidho0403 — APPROVED** [review]
LGGGGGGGGGGTM!

**Comment by davidho0403** [comment]
> @pascal910107 do you have better idea?

Noting, looks fine.

**Comment by ridemountainpig** [comment]
[Comment::createComment()](https://trello.com/c/w5hvm4pY/100-commentcreatecomment)

**Pull request merged**
